# 체크리스트
# [x] 설정 -- /_config.yml
# [x] 도메인 -- /CNAME
# [x] 메뉴 구성 -- /_includes/nav.html
# [x] 첫 페이지 제목 -- /index.md
# [x] 아카이브 제목 -- /archives.md
# [x] 샘플 포스트 삭제 -- /_posts/2023-01-29-lorem-ipsum.md

# 운영자 정보
author: "@oxmhpark"

# 웹사이트 정보
title: "스크랩북"
description: "Dr. Mojo's Manuscripts"
lang: "ko"
timezone: "Asia/Seoul"
stylesheet_url: "/assets/style.css"
favicon_url: ""

# 주소체계
url: "https://about.nemorium.net"
enforce_ssl: "https://about.nemorium.net"
baseurl: "/"
permalink: "/:title/"
format:
  date: "%Y.%m.%d."
  read_more:
    label: "더 읽기 &rarr;"
  view_archives:
    url: "/archives/"
    label: "전체 스크랩 목록 보기 &rarr;"

# 댓글 시스템 (https://giscus.app)
giscus:
  src: "https://giscus.app/client.js"
  repo: "nemorium/about.nemorium.net"
  repo_id: "R_kgDOI3ZCuA"
  category: "giscus"
  category_id: "DIC_kwDOI3ZCuM4CT4aY"
  mapping: "pathname"
  theme: "light"
  lang: "ko"
  input_position: "bottom"
  reactions_enabled: 0
  emit_metadata: 0
  loading: "lazy"
  strict: 1
  crossorigin: "anonymous"

# HTML/CSS 파서
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded

# 빌드 타겟
collections:
  pages:
    output: true
    path: _pages
    permalink: "/:title/"
  updates:
    output: true
    path: _updates
    permalink: "/:title/"
  knowledges:
    output: true
    path: _knowledges
    permalink: "/:title/"
  terms:
    output: true
    path: _terms
    permalink: "/:title/"
  concepts:
    output: true
    path: _concepts
    permalink: "/:title/"
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# 플러그인
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
